### ISSUE TITLE
Error on example 

### ISSUE THREAD

**Issue by joshgrift** [ChristophGaukel/ev3-python3#1]
Running macOS 10.12.5 and Python 3.6.1. I copied the second example exactly as it's presented and this is the error I get. I'm assuming it's because it's on my mac? Eitherway. I have pyusb and pyserial both installed already.

```Traceback (most recent call last):
  File "run.py", line 5, in <module>
    jukebox = ev3_sound.Jukebox(protocol=ev3.BLUETOOTH, host='00:16:53:3d:3a:af')
  File "/Users/Josh/Library/Mobile Documents/com~apple~CloudDocs/Storage/Develop/MindStorms/pu/ev3_sound.py", line 113, in __init__
    super().__init__(protocol=protocol, host=host, ev3_obj=ev3_obj)
  File "/Users/Josh/Library/Mobile Documents/com~apple~CloudDocs/Storage/Develop/MindStorms/pu/ev3.py", line 226, in __init__
    self._connect_bluetooth(host)
  File "/Users/Josh/Library/Mobile Documents/com~apple~CloudDocs/Storage/Develop/MindStorms/pu/ev3.py", line 287, in _connect_bluetooth
    self._socket = socket.socket(socket.AF_BLUETOOTH,
AttributeError: module 'socket' has no attribute 'AF_BLUETOOTH'
```

**Comment by Pedro-Beirao** [comment]
Neither Bluetooth and USB work on MacOS (haven't tried wifi), so I decided to try to figure out what's wrong with the USB connection. Turns out the library this uses to connect (libusb) does not work under this conditions on MacOS. So I changed the source code to work with HIDAPI instead of libusb. I am going to post the changes.
