### ISSUE TITLE
Error when using Touch sensor with Light Sensor

### ISSUE THREAD

**Issue by sebastian-ruiz** [ChristophGaukel/ev3-python3#6]
I am using the original ev3 sensors.

With touch sensor in ev3.PORT_1 and light sensor in ev3.PORT_4 and running the following code:

```
my_color = ev3.Color(
        ev3.PORT_4,
        protocol=ev3.USB
)

print(f'reflected intensity is {my_color.reflected} %')

my_touch = ev3.Touch(
        ev3.PORT_1,
        protocol=ev3.USB
)
print('touched' if my_touch.touched else 'not touched')
```
I get the following error:

```
reflected intensity is 82 %
Traceback (most recent call last):
  File "/home/pi/Documents/ev3-python3/main.py", line 38, in <module>
    protocol=ev3.USB
  File "/usr/local/lib/python3.7/dist-packages/ev3_dc/touch.py", line 71, in __init__
    verbosity=verbosity
  File "/usr/local/lib/python3.7/dist-packages/ev3_dc/ev3.py", line 829, in __init__
    self._physical_ev3 = _PhysicalEV3(protocol, host)
  File "/usr/local/lib/python3.7/dist-packages/ev3_dc/ev3.py", line 150, in __init__
    self.connect_usb()
  File "/usr/local/lib/python3.7/dist-packages/ev3_dc/ev3.py", line 350, in connect_usb
    f"host {self._host} already connected, call with argument ev3_obj"
AssertionError: host 00:16:53:62:F2:EE already connected, call with argument ev3_obj
Exception ignored in: <function Touch.__del__ at 0x7fa72108c8>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/ev3_dc/touch.py", line 110, in __del__
    [self._port]['used_by'] = None
AttributeError: 'NoneType' object has no attribute '_introspection'
```

when I comment out the color sensor part of the code, the touch sensor works. Somehow the color sensor code is messing with the touch sensor. What am I doing wrong?

Thanks for the great library!

**Comment by sebastian-ruiz** [comment]
I found the solution looking at the docs for the PID controller:

```python
with ev3.EV3(protocol=ev3.USB) as my_ev3:

    my_color = ev3.Color(
            ev3.PORT_4,
            ev3_obj=my_ev3
    )

    my_touch = ev3.Touch(
            ev3.PORT_1,
            ev3_obj=my_ev3
    )

    print(f'reflected intensity is {my_color.reflected} %')
    print('touched' if my_touch.touched else 'not touched')
```

**Comment by ChristophGaukel** [comment]
Hello Sebastian,
yes, exactly! Multiple objects like EV3, Touch or Color share a single connection (if you read the code, you will find a class PhysicalEV3). Therefore the first object establishes the connection (in your case an EV3), the other objects (Color and Touch) use the already established connection. It's good coding style to use the with-as
